gboolean myFunction(gchar* filename)
{
	FILE* file = fopen(filename,"w");

	if(file==NULL)
	{
		return FALSE;
	}
	fprintf(file,"#RunType = Energy, Optimization, MD, MDConfo\n");
	fprintf(file,"RunType=MDConfo\n");
	fprintf(file,"#Model = MM , Mopac , Orca or FireFly\n");
	fprintf(file,"Model=Mopac\n");
	fprintf(file,"#SEKeys=PM6\n");
	fprintf(file,"SEKeys=AM1\n");
	fprintf(file,"mopacCommand=/opt/mopac/MOPAC2009.exe\n");
	fprintf(file,"orcaCommand=orca\n");
	fprintf(file,"fireflyCommand=firefly\n");
	fprintf(file,"\n");
	fprintf(file,"#Confo\n");
	fprintf(file,"gaussianCommand=g03\n");
	fprintf(file,"fireflyCommand=firefly\n");
	fprintf(file,"numberOfGeometries=20\n");
	fprintf(file,"tolEnergy=0.01\n");
	fprintf(file,"tolDistance=0.1\n");
	fprintf(file,"#ConfoOptMM=FALSE\n");
	fprintf(file,"ConfoOptMopac=TRUE\n");
	fprintf(file,"ConfoOptMopacMethod=PM6 GNORM=0.001\n");
	fprintf(file,"ConfoOptFireFly=FALSE\n");
	fprintf(file,"# remove # if post processing required\n");
	fprintf(file,"#mopacKeywordsPost=PM6\n");
	fprintf(file,"gaussianKeywordsPost=B3LYP/6-31G*\n");
	fprintf(file,"#fireflyKeywordsPost=AM1\n");
	fprintf(file,"\n");
	fprintf(file,"#MM\n");
	fprintf(file,"# AMBER, UFF(not implemented), PAIRWISE\n");
	fprintf(file,"ForceFieldType=0\n");
	fprintf(file,"ForceFieldUseBond=TRUE\n");
	fprintf(file,"ForceFieldUseBend=TRUE\n");
	fprintf(file,"ForceFieldUseDihedral=TRUE\n");
	fprintf(file,"ForceFieldUseImproper=FALSE\n");
	fprintf(file,"ForceFieldUseNonBonded=TRUE\n");
	fprintf(file,"ForceFieldUseHydrogenBonded=FALSE\n");
	fprintf(file,"ForceFieldUsecoulomb=TRUE\n");
	fprintf(file,"ForceFieldUseVanderWals=TRUE\n");
	fprintf(file,"#  NOCONSTRAINTS = 0, BONDSCONSTRAINTS = 1, BONDSANGLESCONSTRAINTS = 2\n");
	fprintf(file,"ForceFieldConstraints=0\n");
	fprintf(file,"\n");
	fprintf(file,"#MD\n");
	fprintf(file,"updateFrequency=5\n");
	fprintf(file,"heatTime = 0\n");
	fprintf(file,"equiTime = 0\n");
	fprintf(file,"runTime = 1\n");
	fprintf(file,"coolTime = 0\n");
	fprintf(file,"heatTemp = 0\n");
	fprintf(file,"runTemp = 300\n");
	fprintf(file,"stepSize = 0.5\n");
	fprintf(file,"#  VERLET = 0, BEEMAN = 1, STOCHASTIC = 2\n");
	fprintf(file,"integrator = 0\n");
	fprintf(file,"#  NONE = 0, ANDERSEN = 1, BERENDSEN = 2\n");
	fprintf(file,"thermostat = 0\n");
	fprintf(file,"friction=40\n");
	fprintf(file,"collide = 20\n");
	fprintf(file,"\n");
	fprintf(file,"#QuasiNewton\n");
	fprintf(file,"useQuasiNewton = TRUE\n");
	fprintf(file,"quasiNewtonMaxIterations = 100\n");
	fprintf(file,"quasiNewtonUpdateFrequency = 1\n");
	fprintf(file,"quasiNewtonEpsilon  = 0.001\n");
	fprintf(file,"quasiNewtonTolerence = 1e-16\n");
	fprintf(file,"quasiNewtonMaxLines =  25\n");
	fprintf(file,"\n");
	fprintf(file,"#ConjugateGradient\n");
	fprintf(file,"useConjugateGradient = FALSE\n");
	fprintf(file,"conjugateGradientGradientNorm = 1e-3\n");
	fprintf(file,"conjugateGradientMaxIterations = 100\n");
	fprintf(file,"conjugateGradientUpdateFrequency = 1\n");
	fprintf(file,"conjugateGradientMaxLines = 25\n");
	fprintf(file,"conjugateGradientInitialStep = 0.001\n");
	fprintf(file,"# 1 : Hestenes Stiefel,  2 : Fletcher Reeves, 3 : Polak Ribiere, 4 : Wolf Powell\n");
	fprintf(file,"conjugateGradientMethod = 1\n");
	fprintf(file,"\n");
	fprintf(file,"#Geometry, nAtoms, charge, spin multiplicity. For each atom : symbol, MMType, pdbType, residueName, numResidue, charge, layer, x(Ang),y,z, nconn, num1, type1, num2, type2,...\n");
	fprintf(file,"Geometry\n");
	fprintf(file,"3 0 1\n");
	fprintf(file,"O OW OW HOH 0 -0.834000 2 -0.000000 -0.388000 0.000000  2  2 1 3 1\n");
	fprintf(file,"H HW HW1 HOH 0 0.417000 2 0.751000 0.194000 0.000000  1  1 1\n");
	fprintf(file,"H HW HW2 HOH 0 0.417000 2 -0.751000 0.194000 0.000000  1  1 1\n");
	fprintf(file,"\n");
	fprintf(file,"\n");
	fclose(file);
	return TRUE;
}
