/******************************************************************************/
static void save_atom_pdb_file(FILE* file, 
		gchar*name, gint atomNumber,
		gchar* atomType, gchar* residueName,
		gint residueNumber,
		gdouble x, gdouble y, gdouble z,
		gdouble occupancy,
		gdouble temperature,
		gchar* symbol,
		gdouble charge
		)
{
	gchar localName[MAXNAME+1];
	gchar localAtomType[MAXATOMTYPE+1];
	gchar localResidueName[MAXRESIDUENAME+1];
	gchar localSymbol[MAXSYMBOL+1];

	localName[MAXNAME] = '\0';
	localAtomType[MAXATOMTYPE] = '\0';
	localResidueName[MAXRESIDUENAME] = '\0';
	localSymbol[MAXSYMBOL] = '\0';

	if(strlen(name)>MAXNAME)
		strncpy(localName, name, MAXNAME);
	else
		strcpy(localName, name);
	g_strup(localName);

	if(strlen(atomType)>MAXATOMTYPE)
	{
		strncpy(localAtomType, atomType, MAXATOMTYPE);
	}
	else
	{
		if(atomType && isdigit(atomType[0])) strcpy(localAtomType,atomType);
		else 
		{
			sprintf(localAtomType," %s",atomType);
			if(strlen(localAtomType)>=MAXATOMTYPE)
			{
				if(isdigit(localAtomType[MAXATOMTYPE]))
					localAtomType[0] = localAtomType[MAXATOMTYPE];
				localAtomType[MAXATOMTYPE] = '\0';
			}
		}
	}

	if(strlen(residueName)>=MAXRESIDUENAME)
		strncpy(localResidueName, residueName, MAXRESIDUENAME);
	else
	{
		sprintf(localResidueName," %s",residueName);
		if(strlen(localResidueName)>=MAXRESIDUENAME)
		{
			if(isdigit(localResidueName[MAXRESIDUENAME]))
				localResidueName[0] = localResidueName[MAXRESIDUENAME];
			localResidueName[MAXRESIDUENAME] = '\0';
		}
	}
	g_strup(localResidueName);

	if(strlen(symbol)>MAXSYMBOL)
		strncpy(localSymbol, symbol, MAXSYMBOL);
	else
		strcpy(localSymbol,symbol);
	localSymbol[0] = toupper(localSymbol[0]);
	if(strlen(localSymbol)>1)
		localSymbol[1] = tolower(localSymbol[1]);

	if(atomNumber>99999)
		atomNumber = 99999;
	if(residueNumber>9999)
		residueNumber = 9999;


        fprintf(file,"%-6s",localName); /* Atom or HETATM */
        fprintf(file,"%-6d",atomNumber); 
        fprintf(file,"%-4s",localAtomType); 
        fprintf(file,"%-4s",localResidueName); 
        fprintf(file,"  "); 
        fprintf(file,"%-4d",residueNumber); 
        fprintf(file,"    "); 
        fprintf(file,"%-8.3f",x); 
        fprintf(file,"%-8.3f",y); 
        fprintf(file,"%-8.3f",z); 
        fprintf(file,"%-6.2f",occupancy); 
        fprintf(file,"%-6.2f",temperature); 
        fprintf(file,"      "); 
        fprintf(file,"    "); 
        fprintf(file,"%-2s",localSymbol); 
        fprintf(file,"%-9.4f\n",charge); 
}
/********************************************************************************/
static gboolean save_geometry_MD_pdb_format(gchar *FileName)
{
 	FILE *file;
	gint j;
	gboolean OK = TRUE;
	gchar* temp = NULL;

	if(geometriesMD.numberOfGeometries<1) return FALSE;
 	file = FOpen(FileName, "w");
	if(file == NULL)
	{
		gchar buffer[BSIZE];
		sprintf(buffer,"Sorry, I  can not create '%s' file\n",FileName);
  		Message(buffer,"Error",TRUE);
		return FALSE;
	}
	fprintf(file,"HEADER    PROTEIN\n");
	fprintf(file,"COMPND    UNNAMED\n");
	temp = get_time_str();
	if(temp) fprintf(file,"AUTHOR    GENERATED BY GABEDIT %d.%d.%d at %s",MAJOR_VERSION,MINOR_VERSION,MICRO_VERSION,temp);
	else fprintf(file,"AUTHOR    GENERATED BY GABEDIT %d.%d.%d\n",MAJOR_VERSION,MINOR_VERSION,MICRO_VERSION);
	for(j=0;j<geometriesMD.numberOfGeometries;j++)
	{
		gint i;
		gint nAtoms = geometriesMD.geometries[j].numberOfAtoms;
		AtomMD* listOfAtoms = geometriesMD.geometries[j].listOfAtoms;
		if(nAtoms<1 || !listOfAtoms) { OK = FALSE; break;}
		fprintf(file,"TITLE nAtoms=%d Time=%lf Energy=%lf\n", nAtoms,geometriesMD.geometries[j].time, geometriesMD.geometries[j].energy);
		fprintf(file,"REMARK %s\n", geometriesMD.geometries[j].comments);
		fprintf(file,"REMARK %s\n", geometriesMD.geometries[j].comments);
		fprintf(file,"MODEL %d\n", j);

		for(i=0;i<nAtoms;i++)
		{
			gdouble X = listOfAtoms[i].C[0]*BOHR_TO_ANG;
			gdouble Y = listOfAtoms[i].C[1]*BOHR_TO_ANG;
			gdouble Z = listOfAtoms[i].C[2]*BOHR_TO_ANG;
			save_atom_pdb_file(file,"ATOM",i+1,listOfAtoms[i].pdbType,listOfAtoms[i].resName,
			listOfAtoms[i].resNumber+1, X,Y,Z,
			1.0, 300.0, listOfAtoms[i].symbol, atof(listOfAtoms[i].partialCharge));
		}
		fprintf(file,"TER\n");
		fprintf(file,"ENDMDL\n");
	}
	fclose(file);
	return OK;
}
